team-inplace/inplace

- .hooks/README.md
- .hooks/prepare-commit-msg
> [INPLACE-29] Commit 컨벤션 관련 .hooks 추가

- .github/workflows/gradle.yml
> [INPLACE-18] cicd 브랜치명 수정

- .github/workflows/gradle.yml
> [INPLACE-35] 백엔드 cicd 폴더 설정 추가

- .github/workflows/gradle.yml
> [INPLACE-35] 백엔드 cicd 폴더 설정 추가2

- backend/build.gradle
- backend/src/main/resources/application-monitoring.yaml
- backend/src/main/resources/application.yaml
> [INPLACE-16] 모니터링 툴 추가

- .github/workflows/backend-ci-cd.yml
- backend/src/main/resources/application-monitoring.yaml
> [INPLACE-35] 모니터링 PATH설정 변경

- frontend/src/api/hooks/usePatchNickname.ts
- frontend/src/components/Detail/VisitModal.tsx
> [INPLACE-36] 닉네임, 방문할래요 모달 버그 수정

- frontend/src/api/hooks/usePatchNickname.ts
- frontend/src/components/Detail/VisitModal.tsx
- frontend/src/components/Main/MainBanner/BannerItem.tsx
- frontend/src/components/Main/MainBanner/index.tsx
- frontend/src/mocks/mainHandlers.ts
---
모바일 뷰 아직 구현 안해서 현재 첫 배너는 두칸짜리입니다
그리고 이전거 머지 안 한 상태로 브랜치 파서 커밋 기록이 같이 들어있네요ㅋㅋ 무시하심 됩니다
---
---
> [INPLACE-37] 배너를 두개로 분할

- frontend/src/components/Detail/VisitModal.tsx
> [INPLACE-44] 방문할래요 모달 버그 재수정

- .github/workflows/backend-ci-cd.yml
> [INPLACE-35] 환경 변수에서 괄호 제거

- .github/workflows/backend-ci-cd.yml
> INPLACE-19 백엔드 인스턴스 분리

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] aws 자격 증명, 태그 업데이트 단계 추가

- .github/workflows/backend-ci-cd-production.yml
- .github/workflows/backend-ci-cd-test.yml
> [INPLACE-47] Test서버 CI/CD 추가

- .github/workflows/backend-ci-cd.yml
> INPLACE-19 ssh 순서 변경, 문법 수정

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] secrets으로 수정

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] secrets으로 수정2

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 변수 수정

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 조건문 출력 추가

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 타겟 인스턴스 변수 수정

- .github/workflows/frontend-ci-cd.yml
> [INPLACE-47] 프론트엔드 ci/cd 워크플로우 수정

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 컨테이너 삭제 서버 변경

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 모든 규칙의 타겟그룹이 변경되도록 수정

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 큰따옴표 추가

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 규칙 가져오기 구조 변경

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 규칙 가져오기 배열로 변경

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 시크릿 이름 변경

- .github/workflows/backend-ci-cd.yml
> [INPLACE-19] 헬스체크 포트 분리

- .github/workflows/backend-ci-cd-test.yml
> [INPLACE-52] Sudo 명령어 추가

- backend/src/main/resources/config/dev/application-db.yaml
> [INPLACE-52] yaml파일에 ddl-auto명령어 추가

- backend/src/main/java/team7/inplace/security/config/CorsConfig.java
- backend/src/main/java/team7/inplace/security/config/SecurityConfig.java
- Dev서버에 대한 Cors 처리 추가
- Request Header로 변경
- Dev와 Prod Bean분리
---
---
---
> [INPLACE-46] Security 에러 수정

- backend/src/main/java/team7/inplace/security/config/CorsConfig.java
- Local Cors설정 추가
- 공통 설정 부분 매서드 분리
---
---
---
> [INPLACE-62] Local Cors 설정 추가

- backend/src/main/java/team7/inplace/security/config/CorsConfig.java
> [INPLACE-87] CORS 에러 해결시도

- backend/src/main/java/team7/inplace/admin/AdminPageController.java
- backend/src/main/java/team7/inplace/admin/crawling/client/YoutubeClient.java
- backend/src/main/java/team7/inplace/influencer/application/InfluencerService.java
- backend/src/main/java/team7/inplace/place/application/command/PlacesCommand.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceSaveRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- backend/src/main/java/team7/inplace/video/application/VideoFacade.java
> [INPLACE-87] 크롤링 로직 및 장소 조회 로직 수정

- backend/src/main/java/team7/inplace/security/config/CorsConfig.java
- backend/src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
- backend/src/main/java/team7/inplace/security/util/CookieUtil.java
- backend/src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
- backend/src/main/resources/application-security.yaml
- 쿠키 설정을 변경합니다.(inplace.my를 도메인으로 사용하도록 합니다.)
---
---
---
> [INPLACE-87] 쿠키 설정 변경

- frontend/src/App.tsx
- frontend/src/api/hooks/useGetInfluencerInfo.ts
- frontend/src/api/hooks/useGetInfluencerVideo.ts
- frontend/src/components/InfluencerInfo/InfluencerMapTap/index.tsx
- frontend/src/components/InfluencerInfo/InfluencerVideoTap/index.tsx
- frontend/src/components/Main/SpotSection/SpotItem.tsx
- frontend/src/components/common/Items/InfluencerItem.tsx
- frontend/src/mocks/influencerHandlers.ts
- frontend/src/pages/InfluencerInfo/index.tsx
- frontend/src/types/index.ts
---
- id 1번 성시경 걸로 보면 됩니다
- 지도는 클러스터러 변경 전이라서 기본 지도만 박아두었습니당
---
---
> [INPLACE-79] 인플루언서 전용 페이지 구현

- .github/workflows/frontend-ci-cd.yml
- frontend/src/api/config/index.ts
- frontend/src/components/InfluencerInfo/InfluencerMapTap/index.tsx
> [INPLACE-89] 변경된 dev용 서버를 반영하도록 ci/cd 수정

- .github/workflows/frontend-ci-cd.yml
- frontend/src/api/config/index.ts
- frontend/src/components/InfluencerInfo/InfluencerMapTap/index.tsx
> [INPLACE-89] 빌드 명령어에 조건문 추가

- backend/src/main/java/team7/inplace/token/application/RefreshTokenFacade.java
- backend/src/main/java/team7/inplace/token/application/RefreshTokenService.java
- backend/src/main/java/team7/inplace/token/domain/RefreshToken.java
> [INPLACE-97] 토큰 검증 방식 변경

- backend/src/main/java/team7/inplace/security/util/JwtUtil.java
- backend/src/main/java/team7/inplace/token/application/RefreshTokenService.java
> [INPLACE-97] INVALID TOKEN 발생 지점에 log 추가

- backend/src/main/java/team7/inplace/token/application/RefreshTokenService.java
- backend/src/main/java/team7/inplace/token/domain/RefreshToken.java
- backend/src/main/java/team7/inplace/token/persistence/RefreshTokenRepository.java
> [INPLACE-97] 토큰이 저장이 되었는지 확인하는 로그 추가

- backend/src/main/java/team7/inplace/video/persistence/VideoReadRepositoryImpl.java
- 반경 3KM정도로 변경하였습니다.
---
---
---
> [INPLACE-94] 비디오(장소) 조회 로직 탐색 범위 변경

- backend/src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
> [INPLACE-98] 로그아웃 CORS 해결

- backend/src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
- 프론트엔드와 합의 후 프론트엔드에서 리다이렉트 하도록 변경
---
---
---
> [INPLACE-98] CORS에러로 인해 리다이렉션 삭제

- backend/src/main/java/team7/inplace/search/presentation/SearchController.java
> [INPLACE-87] 누락된 RequestParam 추가

- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- 장소 세부 조회 시 influencerName, videoUrl response 변경
---
- 코드 스타일 구글 맞나요...
---
---
> [INPLACE-85] 장소 세부 조회 시 response 변경

- frontend/src/api/hooks/useGetAllMarkers.ts
- frontend/src/api/hooks/useGetInfinitePlaceList.ts
- frontend/src/api/hooks/useGetInfluencerInfo.ts
- frontend/src/components/InfluencerInfo/InfluencerMapTap/InfluencerMapWindow.tsx
- frontend/src/components/InfluencerInfo/InfluencerMapTap/InfoWindow.tsx
- frontend/src/components/InfluencerInfo/InfluencerMapTap/index.tsx
- frontend/src/components/Map/DropdownMenu/DropdownItem.tsx
- frontend/src/components/Map/DropdownMenu/index.tsx
- frontend/src/components/Map/MapWindow/index.tsx
- frontend/src/components/Map/PlaceSection/PlaceItem.tsx
- frontend/src/components/Map/PlaceSection/index.tsx
- frontend/src/components/common/Chip/index.tsx
- frontend/src/mocks/mapHandlers.ts
- frontend/src/pages/InfluencerInfo/index.tsx
- frontend/src/pages/Map/index.tsx
- frontend/src/types/index.ts
---
- 중간에 실수로 브랜치 88이름으로 커밋했네 ㅎㅎ
- 똑같이 제일 밑에있는 마커 누르면 정보 날라오고, 나머지는 아래에 장소정보 있을 경우만 뜸! 마커들 필터링 잘 먹는지는 배포환경에서 테스트 해봐야할듯
---
---
> [INPLACE-100] 지도 페이지 마커 인포메이션 추가

- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImpl.java
> [INPLACE-101] 사용자가 로그인 하지 않았을 경우 처리 추가

- backend/src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
> [INPLACE-93] hotfix - 쿠키 key (ACCESS_TOKEN => access_token)

- backend/src/main/java/team7/inplace/influencer/presentation/InfluencerController.java
> [INPLACE-104] RequestBody 누락 추가

- backend/src/main/java/team7/inplace/influencer/presentation/dto/InfluencerRequest.java
> [INPLACE-106] 인플루언서 좋아요 오류 수정

- backend/src/main/java/team7/inplace/global/baseEntity/BaseEntity.java
- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerRepository.java
- backend/src/main/java/team7/inplace/liked/likedInfluencer/persistent/LikedInfluencerRepository.java
- backend/src/main/java/team7/inplace/liked/likedPlace/persistence/LikedPlaceRepository.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/review/persistence/ReviewJPARepository.java
- backend/src/main/java/team7/inplace/review/persistence/ReviewReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/user/persistence/UserRepository.java
- backend/src/main/java/team7/inplace/video/persistence/VideoReadRepositoryImpl.java
- deleteAt 이 null인 것만 가져오도록 쿼리 수정
- 근데 지금 soft delete 적용된 게 없어서 큰 의미가 없는 듯합니다
---
---
---
> [INPLACE-109] soft delete한 거 쿼리 결과에서 제외하기

- backend/src/main/java/team7/inplace/influencer/presentation/dto/InfluencerRequest.java
- like -> likes로 변경했습니다.
---
---
---
> [INPLACE-106] 단일 인플루언서 좋아요 필드 변경

- frontend/src/components/common/Items/InfluencerItem.tsx
---
- 로컬에서 재렌더링이 되는건 확인했는데, 좋아요 반영 문제라 머지하고 확인해봐야할듯
---
---
> [INPLACE-110] 인플루언서 좋아요시 비디오 즉시 업데이트

- .github/workflows/frontend-ci-cd.yml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/api/instance/index.ts
- frontend/src/components/common/layouts/Error.tsx
- frontend/src/components/common/layouts/MainLayout.tsx
- frontend/src/main.tsx
- frontend/vite.config.ts
---
- env 두 개 더 추가해야함
- 프로덕션 환경에서 받아오므로 머지해야 확인 가능할듯..?
---
---
> [INPLACE-17] 모니터링 툴 Sentry

- backend/src/main/java/team7/inplace/global/exception/code/ReviewErrorCode.java
- backend/src/main/java/team7/inplace/kakao/application/PlaceMessageFacade.java
- backend/src/main/java/team7/inplace/review/application/ReviewInvitationService.java
- backend/src/main/java/team7/inplace/review/application/dto/ReviewInfo.java
- backend/src/main/java/team7/inplace/review/persistence/ReviewInvitationRepository.java
- backend/src/main/java/team7/inplace/review/presentation/ReviewController.java
- backend/src/main/java/team7/inplace/review/presentation/ReviewControllerApiSpec.java
- backend/src/main/java/team7/inplace/review/presentation/dto/ReviewResponse.java
- 기존에 있던 Repository를 재사용했는데 필요 시 Repository 분리하겠습니다.
---
---
---
> [INPLACE-104] UUID로 리뷰 장소 및 사용자 정보 조회 API

- backend/src/main/java/team7/inplace/admin/crawling/application/CrawlingFacade.java
- backend/src/main/java/team7/inplace/admin/crawling/application/command/PlaceRegistrationCommand.java
- backend/src/main/java/team7/inplace/admin/crawling/presentation/CrawlingController.java
- backend/src/main/java/team7/inplace/admin/crawling/presentation/dto/PlaceRegistrationRequest.java
- backend/src/main/java/team7/inplace/place/application/command/PlacesCommand.java
- backend/src/main/resources/static/css/login.css
- backend/src/main/resources/static/css/style.css
- backend/src/main/resources/static/js/video.js
- backend/src/main/resources/templates/admin/login.html
- backend/src/main/resources/templates/admin/video.html
- admin/video.html 파일을 수정하였습니다.
- 이제 장소를 등록할 때 카테고리를 선택하여야 합니다.
---
---
---
> [INPLACE-93] 어드민유저가 장소를 등록할때 카테고리도 정해줘야함.

- backend/src/main/java/team7/inplace/place/application/PlaceService.java
- backend/src/main/java/team7/inplace/review/application/ReviewInvitationService.java
> [INPLACE-117] 누락된 메서드변경 수정

- backend/src/main/java/team7/inplace/search/application/SearchService.java
- Paging 로직을 변경했스빈다.
---
---
---
> [INPLACE-116] 검색 API 오류 수정

- backend/src/main/java/team7/inplace/admin/AdminPageController.java
- backend/src/main/java/team7/inplace/video/application/VideoService.java
- backend/src/main/java/team7/inplace/video/application/command/VideoCommand.java
- backend/src/main/resources/templates/admin/video.html
- 카테고리 정보를 서버에서 받아오도록 수정
---
---
---
> [INPLACE-120] Admin페이지 장소 로직 수정

- frontend/index.html
- frontend/package-lock.json
- frontend/package.json
- frontend/src/api/instance/index.ts
- frontend/src/components/common/BaseLayout.tsx
- frontend/src/components/common/Pagination/index.tsx
- frontend/src/components/common/layouts/Error.tsx
- frontend/src/components/common/layouts/Footer.tsx
- frontend/src/components/common/layouts/Header.tsx
- frontend/src/components/common/layouts/Loading.tsx
- frontend/src/components/common/layouts/NoItem.tsx
- frontend/src/components/common/modals/LoginModal.tsx
- frontend/src/components/common/typography/Text.tsx
- frontend/src/main.tsx
- frontend/src/mocks/detailHandlers.ts
- frontend/src/pages/Choice/index.tsx
- frontend/vite.config.ts
---
- referrer 안먹힙니다~..
---
---
> [INPLACE-123] Hotfix referrer 헤더 제거

- backend/src/main/java/team7/inplace/place/domain/Category.java
- 장소 카테고리를 추가했습니다.
- Database도 수정 완료했습니다.
---
---
---
> [INPLACE-121] 장소 카테고리 추가

- backend/src/main/java/team7/inplace/admin/crawling/application/CrawlingFacade.java
- backend/src/main/java/team7/inplace/place/application/PlaceService.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceJpaRepository.java
- backend/src/main/java/team7/inplace/video/application/VideoService.java
- backend/src/main/java/team7/inplace/video/persistence/VideoRepository.java
- backend/src/test/java/team7/inplace/place/application/PlaceServiceTest.java
- 장소가 이미 있는 경우 연결하도록 수정하였습니다.
- 비디오가 이미 존재하는경우 연결하지 않도록 수정하였습니다.
---
---
---
> [INPLACE-125] 장소와 비디오가 이미 있는경우 추가하지 않도록 변경

- backend/src/main/java/team7/inplace/admin/banner/presentation/BannerController.java
- backend/src/main/java/team7/inplace/admin/crawling/presentation/CrawlingController.java
- backend/src/main/java/team7/inplace/global/exception/InplaceExceptionHandler.java
- backend/src/main/java/team7/inplace/influencer/presentation/InfluencerController.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
- backend/src/main/java/team7/inplace/review/application/ReviewService.java
- backend/src/main/java/team7/inplace/review/persistence/ReviewReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/review/presentation/ReviewController.java
- backend/src/main/java/team7/inplace/security/handler/CustomAccessDeniedHandler.java
- backend/src/main/java/team7/inplace/security/handler/CustomFailureHandler.java
- backend/src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
- backend/src/main/java/team7/inplace/user/presentation/UserController.java
- backend/src/main/java/team7/inplace/video/presentation/VideoController.java
- preAuthorize를 Handler에서 핸들링하도록 변경
- API에 PreAuthorize 설정
---
---
---
> [INPLACE-114] API호출 권한 수정

- backend/src/main/java/team7/inplace/admin/banner/presentation/BannerController.java
- 배너의 Get권한을 수정합니다.
---
---
---
> [INPLACE-128] Banner 권한 수정

- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- PlaceLikes의 형식을 Long으로 변경하였습니다.
---
---
---
> [INPLACE-127] 장소 반환 API의 형식을 변경

- .github/workflows/frontend-ci-cd.yml
- frontend/index.html
- frontend/package-lock.json
- frontend/package.json
- frontend/public/sitemap.xml
- frontend/vite.config.ts
> [INPLACE-129] 검색 엔진 최적화

- frontend/src/api/hooks/useGetInfluencerVideo.ts
- frontend/src/mocks/influencerHandlers.ts
- frontend/src/pages/InfluencerInfo/index.tsx
> [INPLACE-131] 인플 전용 페이지 비디오 호출 경로 수정

- backend/src/main/java/team7/inplace/influencer/application/InfluencerService.java
- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerReadRepository.java
- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
- backend/src/main/java/team7/inplace/place/application/PlaceService.java
- backend/src/main/java/team7/inplace/place/application/dto/PlaceQueryInfo.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepository.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/persistence/dto/PlaceQueryResult.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- marker
```
GET places/{placeId}/marker
**Response**
json
{
placeId: number,
placeName: string,
category: string,
influencerName: string, <= 인플루언서들의 이름이 ,로 연결되어있습니다.
address: {
address1 : string,
address2 : string,
address3 : string
},
menuImgUrl: string
}
```
위와 같은 형식으로 반환됩니다.
- category를 반환하면 api 들은 영어(변경 전) => 한국어(변경 후) 로 반환됩니다.
---
---
---
> [INPLACE-102] marker를 위한 장소정보를 반환하는 api를 작성하였습니다.

- frontend/src/App.tsx
- frontend/src/api/hooks/useGetReviewInfo.ts
- frontend/src/api/hooks/usePostPlaceReview.ts
- frontend/src/components/Detail/InfoTap/FacilitySign.tsx
- frontend/src/components/Detail/InfoTap/MenuModal.tsx
- frontend/src/components/Detail/InfoTap/index.tsx
- frontend/src/components/Map/DropdownMenu/DropdownItem.tsx
- frontend/src/components/Map/DropdownMenu/index.tsx
- frontend/src/components/Map/MapWindow/index.tsx
- frontend/src/components/Map/PlaceSection/PlaceItem.tsx
- frontend/src/components/Map/PlaceSection/index.tsx
- frontend/src/components/common/Chip/index.tsx
- frontend/src/components/common/layouts/Footer.tsx
- frontend/src/hooks/useExtractYoutube.tsx
- frontend/src/mocks/mapHandlers.ts
- frontend/src/pages/Detail/index.tsx
- frontend/src/pages/Map/index.tsx
- frontend/src/utils/constants/CategoryOptions.ts
- 지도페이지의 모바일 뷰
---
- 지도페이지 모바일뷰 드래그 잘 되는지 확인 한 번 부탁해!
- 카테고리 필터링 잘 되는지 확인은 api에서 해당 카테고리가 담겨져서 api 호출하는지 확인하면 될 듯!
---
---
> [INPLACE-124] QA 환경에서 발생하는 버그 해결

- frontend/src/api/hooks/useGetInfluencerVideo.ts
- frontend/src/mocks/influencerHandlers.ts
- frontend/src/pages/InfluencerInfo/index.tsx
> [INPLACE-133] 인플루언서 id를 쿼리 키에 추가

- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/video/persistence/VideoReadRepositoryImpl.java
- backend/src/test/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImplTest.java
- backend/src/test/resources/sql/test-influencer.sql
- 비디오 조회 시 place_id가 null인 경우를 제외하도록 innerJoin으로 변경
- 인플루언서의 팔로워와 비디오 수 조회를 Scalar SubQuery로 변경하였습니다.
---
---
---
> [INPLACE-130] 인플루언서 정보 및 비디오 조회 API 수정

- frontend/index.html
- frontend/src/api/hooks/useGetDropdownName.ts
- frontend/src/api/hooks/useGetInfluencerVideo.ts
- frontend/src/components/Map/DropdownMenu/DropdownItem.tsx
- frontend/src/components/Map/DropdownMenu/index.tsx
- frontend/src/components/Map/MapWindow/index.tsx
- frontend/src/components/common/Chip/index.tsx
- frontend/src/global.ts
- frontend/src/mocks/influencerHandlers.ts
- frontend/src/pages/InfluencerInfo/index.tsx
- frontend/src/pages/Map/index.tsx
> [INPLACE-133] influencer video 버그 및 자잘한 버그 수정

- backend/src/test/java/team7/inplace/video/persistence/VideoReadRepositoryTest.java
- backend/src/test/resources/sql/test-video.sql
- 비디오 도메인 테스트 작성
- 장소 범위로 비디오 조회 시, 경계값 사용이 필요 없음
- 더미 데이터 작성시, 한글 사용이 안되는 로컬 문제 있음 ( 고치지는 않아도 될듯 )
> [INPLACE-81] 비디오 도메인 테스트

- backend/src/main/java/team7/inplace/review/persistence/ReviewReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/user/presentation/UserController.java
- backend/src/main/java/team7/inplace/user/presentation/UserControllerApiSepc.java
- backend/src/main/java/team7/inplace/user/presentation/dto/UserRequest.java
- 유저 닉네임 변경 API 수정
- 유저 리뷰 조회 쿼리 수정
---
---
---
> [INPLACE-136] 마이페이지 API 오류 수정

- backend/src/main/java/team7/inplace/user/presentation/UserController.java
> [INPLACE-136] 오타 수정

- backend/src/main/java/team7/inplace/review/persistence/ReviewReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/user/presentation/dto/UserResponse.java
- 리뷰 조회 쿼리를 수정하였습니다.
---
---
---
> [INPLACE-136] 리뷰 조회 쿼리 수정

- frontend/src/api/hooks/usePatchNickname.ts
- frontend/src/components/InfluencerInfo/InfluencerMapTap/InfluencerMapWindow.tsx
- frontend/src/components/InfluencerInfo/InfluencerMapTap/InfluencerPlaceSection.tsx
- frontend/src/components/InfluencerInfo/InfluencerMapTap/index.tsx
- frontend/src/components/InfluencerInfo/InfluencerVideoTap/index.tsx
- frontend/src/components/Map/DropdownMenu/index.tsx
- frontend/src/components/Map/MapWindow/index.tsx
- frontend/src/components/Map/PlaceSection/PlaceItem.tsx
- frontend/src/components/Map/PlaceSection/index.tsx
- frontend/src/components/common/Chip/index.tsx
- frontend/src/components/common/layouts/Error.tsx
- frontend/src/mocks/myPageHandlers.ts
- frontend/src/pages/Map/index.tsx
- frontend/src/utils/test/testUtils.tsx
> [INPLACE-135] 지도 영역 스크롤 추가

- backend/src/main/java/team7/inplace/user/presentation/dto/UserResponse.java
- API Response 및 필드 추가
---
---
---
> [INPLACE-139] 좋아요한 인플루언서 정보반환 API 수정

- backend/src/test/java/team7/inplace/influencer/application/InfluencerServiceTest.java
> [INPLACE-80] 인플루언서 테스트

- backend/src/main/java/team7/inplace/place/application/PlaceService.java
- backend/src/main/java/team7/inplace/review/persistence/ReviewReadRepositoryImpl.java
- backend/src/test/java/team7/inplace/review/application/ReviewServiceTest.java
- backend/src/test/java/team7/inplace/review/persistence/ReviewReadRepositoryImplTest.java
- backend/src/test/resources/sql/test-review.sql
- 리뷰 LikeRate 반환 쿼리 오류 수정 -> 확인 함 해주세요
- ReviewReadRepository 테스트
- ReviewService 테스트
---
- 리뷰 초대 링크 관해서는 레디스 레포지토리 테스트하는 법 알아보고 추가 예정
---
---
> [INPLACE-83] 리뷰 테스트

- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/persistence/dto/PlaceQueryResult.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- Repository에서 String형태가 아닌 Category로 받아오도록 변경
- Dto에서 name을 반환하도록 변경
---
---
---
> [INPLACE-145] Category를 한글로 반환하도록 변경

- backend/src/main/java/team7/inplace/global/exception/code/KakaoMessageErrorCode.java
- backend/src/main/java/team7/inplace/kakao/application/KakaoMessageService.java
- backend/src/main/java/team7/inplace/kakao/application/PlaceMessageFacade.java
- backend/src/main/java/team7/inplace/kakao/application/command/PlaceMessageCommand.java
- backend/src/main/java/team7/inplace/kakao/domain/MessageSendHistory.java
- backend/src/main/java/team7/inplace/kakao/persistence/MessageSendHistoryRepository.java
- backend/src/main/java/team7/inplace/kakao/presentation/KakaoController.java
- backend/src/main/java/team7/inplace/place/application/PlaceService.java
- backend/src/main/java/team7/inplace/token/application/OauthTokenService.java
- backend/src/main/java/team7/inplace/video/application/AliasUtil.java
- 할당량을 10회로 설정했습니다.
---
- 메시지 생성 command 로직을 수정하였습니다.
- 추후 메시지 전송 시 주소가 아닌 매장 링크로 메시지를 전송하기 위하여 PlaceInfo.Detail로 변경하였습니다.
---
---
> [INPLACE-144] 나에게 장소 정보 보내기 할당량 설정

- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- rating 필드를 추가했습니다.
---
---
---
> [INPLACE-146] Place response에 구글 평점 추가

- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- response 필드 placeLIke -> placeLikes로 수정
---
---
---
> [INPLACE-146] response 필드명 수정

- backend/src/main/java/team7/inplace/user/presentation/dto/UserResponse.java
> [INPLACE-147] address를 클래스로 반환하도록 변경

- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- like 필드를 추가했습니다.
---
---
---
> [INPLACE-149] API Response에 like필드 추가

- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
- backend/src/main/java/team7/inplace/place/client/GooglePlaceClientResponse.java
- backend/src/main/java/team7/inplace/place/persistence/dto/PlaceQueryResult.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- googlePlaceId가 null인 경우 처리를 추가하였습니다.
- google API의 Review필드가 null인 경우 처리를 추가했습니다.
---
---
---
> [INPLACE-151] Place 관련 null처리 추가

- .github/workflows/backend-ci-cd-production.yml
> [Hotfix!] CI/CD 변수명 변경

- .github/workflows/backend-ci-cd-production.yml
> [Hotfix!] 로그 추가

- .github/workflows/backend-ci-cd-production.yml
> [Hotfix!] TargetInsatance 변수 분리

- .github/workflows/backend-ci-cd-production.yml
> [Hotfix!] 변수명 수정

- backend/src/main/java/team7/inplace/security/config/CorsConfig.java
> [INPLACE-156] Sentry관련 헤더 추가

- backend/src/main/java/team7/inplace/security/config/CorsConfig.java
> [INPLACE-156] Sentry관련 헤더 추가 (#172)

- .github/workflows/backend-ci-cd-production.yml
> [INPLACE-157] 종료하는 instance 변경

- .github/workflows/backend-ci-cd-production.yml
- backend/src/main/java/team7/inplace/security/config/CorsConfig.java
> [INPLACE-157] Production CICD 수정

- .github/workflows/backend-ci-cd-production.yml
> [INPLACE-157] 인스턴스 id 에서 host를 검색하도록 수정

- backend/src/main/java/team7/inplace/security/config/CorsConfig.java
> [INPLACE-157] 인스턴스 id에서 host를 검색하도록 수정

- .github/workflows/backend-ci-cd-production.yml
> [INPLACE-157] cicd 수정

- .github/workflows/backend-ci-cd-production.yml
> [INPLACE-157] known_hosts에 호스트 추가

- .github/workflows/backend-ci-cd-production.yml
> [INPLACE-157] known_hosts에 호스트 추가 (#180)

- backend/src/main/java/team7/inplace/search/persistence/VideoSearchRepository.java
- Search 과정에서 Left Join시에 NPE를 방지하기 위한 부분 추가
- Search 요청을 여러 번 해야 원하는 결과가 나오는 문제가 있음 ( 로컬 기준 )
---
> [INPLACE-158] Search 과정 Null 처리

- backend/src/main/java/team7/inplace/admin/banner/application/BannerService.java
- backend/src/main/java/team7/inplace/admin/banner/application/command/BannerCommand.java
- backend/src/main/java/team7/inplace/admin/banner/application/dto/BannerInfo.java
- backend/src/main/java/team7/inplace/admin/banner/domain/Banner.java
- backend/src/main/java/team7/inplace/admin/banner/presentation/BannerRequest.java
- backend/src/main/java/team7/inplace/admin/banner/presentation/BannerResponse.java
- backend/src/main/java/team7/inplace/global/exception/code/BannerErrorCode.java
- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerRepository.java
- backend/src/main/resources/static/js/banner.js
- backend/src/main/resources/templates/admin/banner.html
- 배너 등록, 반환 시 isMain, isMobile, influencerId 값 추가
---
- 기존 배너 새로 저장해야함
- **imgName을 인플루언서 이름으로 id 찾음**
---
---
> [INPLACE-153] 배너 반환값 추가

- backend/src/main/java/team7/inplace/global/exception/code/KakaoMessageErrorCode.java
- backend/src/main/java/team7/inplace/kakao/application/KakaoMessageService.java
- backend/src/main/java/team7/inplace/kakao/application/PlaceMessageFacade.java
- backend/src/main/java/team7/inplace/kakao/presentation/KakaoController.java
- backend/src/main/java/team7/inplace/kakao/presentation/KakaoControllerApiSpec.java
- backend/src/main/java/team7/inplace/review/presentation/ReviewController.java
- backend/src/main/resources/application-security.yaml
- 카카오톡 나에게 보내기 권한이 없을 시, httpStatus 400을 반환합니다.
- review 와 place Message 기능은 hasRole('ADMIN')으로 설정해두었습니다.
- kakao scope에서 talk-message를 삭제하였습니다.
---
---
---
> [INPLACE-155] place-message 보낼때 error Handling하기

- frontend/public/robots.txt
- frontend/public/sitemap.xml
> [INPLACE-161] sitemap 업데이트

- backend/src/main/java/team7/inplace/global/exception/InplaceExceptionHandler.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
- backend/src/main/java/team7/inplace/security/filter/ExceptionHandlingFilter.java
- backend/src/main/resources/application.yaml
- Controller Advice의 에러메세지를 모두 500으로 수정하였습니다.
- 로그인 에러 메세지도 500으로 수정하였습니다.
- prod 서버는 swagger가 비활성화됩니다
- place save는 admin 권한이 필요합니다.
---
---
---
> [INPLACE-160] 에러 메세지 차단 및 uri 권한 수정

- frontend/index.html
- frontend/public/robots.txt
- frontend/public/sitemap.xml
> [INPLACE-161] 사이트 제목 변경

- backend/src/main/java/team7/inplace/global/exception/DevExceptionHandler.java
> [INPLACE-160] prod서버에서는 상세 에러메시지를 전달하지 않도록 변경

- backend/src/main/java/team7/inplace/global/exception/DevExceptionHandler.java
- backend/src/main/java/team7/inplace/global/exception/InplaceExceptionHandler.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
- backend/src/main/java/team7/inplace/security/filter/ExceptionHandlingFilter.java
- backend/src/main/resources/application.yaml
- frontend/index.html
- frontend/public/robots.txt
- frontend/public/sitemap.xml
- frontend/src/api/hooks/useGetPlaceInfo.ts
- frontend/src/components/Map/PlaceSection/PlaceItem.tsx
> [Release] DEV to PROD 2025-02-20

- frontend/src/components/My/UserPlaceSection/UserPlaceItem.tsx
- frontend/src/pages/Choice/index.tsx
- frontend/src/pages/Detail/index.tsx
> [INPLACE-161] 장소 좋아요 즉시 반영(마이페이지, 세부페이지)

- frontend/index.html
- frontend/src/api/instance/index.ts
- frontend/src/hooks/useGetLocation.ts
- frontend/src/utils/test/testUtils.tsx
> [Release] DEV to PROD 2025-02-21

- backend/build.gradle
- backend/src/main/java/team7/inplace/qrcode/presentation/QRCodeController.java
- backend/src/main/java/team7/inplace/qrcode/presentation/QRCodeControllerApiSpec.java
> [INPLACE-163] Valid 오류 수정

- frontend/src/api/hooks/useGetMobileMapQR.ts
- frontend/src/components/Detail/InfoTap/index.tsx
- frontend/src/components/Detail/VisitModal.tsx
- frontend/src/pages/Detail/index.tsx
> [INPLACE-167] 모바일로 연결해주는 QRcode 기능 구현

- backend/src/main/java/team7/inplace/qrcode/application/QRCodeService.java
- backend/src/main/java/team7/inplace/qrcode/domain/QRCode.java
> [INPLACE-163] 마진이 없도록 변경

- frontend/src/components/InfluencerInfo/InfluencerMapTap/InfluencerMapWindow.tsx
- frontend/src/components/InfluencerInfo/InfluencerMapTap/InfluencerPlaceSection.tsx
- frontend/src/components/InfluencerInfo/InfluencerMapTap/index.tsx
* [INPLACE-166] 현재 위치에서 장소정보 보기 버튼을 placeSection으로 이동
* [INPLACE-166] 충돌 수정하면서 덜 지워진 isListExpanded, onListExpand 삭제
* [INPLACE-166] 장소보기 버튼 패딩 제거 및 리스트와 간격 추가
---
---
---
[INPLACE-166]: https://justnowthatplace.atlassian.net/browse/INPLACE-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INPLACE-166]: https://justnowthatplace.atlassian.net/browse/INPLACE-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INPLACE-166]: https://justnowthatplace.atlassian.net/browse/INPLACE-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Release] DEV to PROD 2025-02-23

- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- place 정보에 naverPlaceId를 추가하였습니다.
- response로 naverPlaceUrl field가 추가되었습니다.
---
---
---
> [INPLACE-172] place 정보 naverPlaceId 추가

- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
- backend/src/main/java/team7/inplace/place/application/dto/PlaceInfo.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/persistence/dto/PlaceQueryResult.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- 장소 정보, 마커 정보에 비디오 정보 추가
---
---
---
> [INPLACE-184] 지도 장소조회 Response 변경

- backend/src/main/java/team7/inplace/global/exception/code/SearchErrorCode.java
- backend/src/main/java/team7/inplace/search/application/SearchService.java
- backend/src/main/java/team7/inplace/search/application/dto/SearchType.java
- backend/src/main/java/team7/inplace/search/presentation/SearchController.java
- backend/src/main/java/team7/inplace/search/presentation/SearchControllerApiSpec.java
- backend/src/main/java/team7/inplace/search/presentation/dto/SearchRequest.java
- Request를 ModelAttribute로 변경
- type이 존재하지 않을 경우 ALL로 변환하도록함.
- ALL과 PLACE만 검색 가능하도록 함.
---
---
---
> [INPLACE-188] 검색어 자동완성에 타입 추가

- backend/src/main/java/team7/inplace/InplaceApplication.java
- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
- backend/src/main/java/team7/inplace/place/application/PlaceService.java
- backend/src/main/java/team7/inplace/place/client/GooglePlaceClient.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceJpaRepository.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceControllerApiSpec.java
- 기존 Mono를 CompletableFuture로 사용하였습니다.
- ForkJoinPool을 사용하도록 설정하였습니다.
---
- 추후 스레드 관리가 필요하면 스레드 풀도 관리할 예정입니다.
---
---
> [INPLACE-191] CompletableFuture로 변경

- backend/src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
- backend/src/main/java/team7/inplace/security/util/CookieUtil.java
- Cookie 세팅 Lax로 변경
- Authorization 필터에서 Referer 확인
---
---
---
> [INPLACE-190] CSRF 방지

- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
> [INPLACE-191] 파라미터 오류 수정

- backend/build.gradle
- backend/src/main/java/team7/inplace/admin/crawling/client/YoutubeClient.java
- backend/src/main/java/team7/inplace/global/annotation/Client.java
- backend/src/main/java/team7/inplace/global/aop/ExecutionTimeAspect.java
- backend/src/main/java/team7/inplace/global/aop/ThreadContextPropagatingDecorator.java
- backend/src/main/java/team7/inplace/global/aop/ThreadExecutionContext.java
- backend/src/main/java/team7/inplace/global/config/AsyncConfig.java
- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
- backend/src/main/java/team7/inplace/place/client/GooglePlaceClient.java
- backend/src/main/java/team7/inplace/security/config/SecurityFilterConfig.java
- backend/src/main/java/team7/inplace/security/filter/ApiExecutionMetricsFilter.java
- ThreadLocal로 모든 Layer 수집하는 AOP추가
- 비동기 스레드 ThreadLocal 공유 추가
---
---
---
> [INPLACE-193] AOP로 메서드별 Execute Time 수집

- .github/workflows/backend-ci-cd-test.yml
- backend/src/main/java/team7/inplace/global/aop/ExecutionTimeAspect.java
- backend/src/main/java/team7/inplace/global/aop/ThreadContextPropagatingDecorator.java
- backend/src/main/java/team7/inplace/global/aop/ThreadExecutionContext.java
- backend/src/main/java/team7/inplace/security/filter/ApiExecutionMetricsFilter.java
- 비동기로 인해 Stack이 제대로 동작하지않아 Tree구조에서 List구조로 변경
---
---
---
> [INPLACE-193] 실행 시간 수집 방식 변경

- backend/src/main/java/team7/inplace/security/filter/ApiExecutionMetricsFilter.java
- 메트릭 수집에 UUID를 추가했스빈다.
- 메트릭 수집 방식을 변경했습니다.
---
---
---
> [INPLACE-193] 메트릭 변경

- backend/src/main/java/team7/inplace/qrcode/application/QRCodeFacade.java
- 쿼리 파라미터 순서를 변경했습니다.
---
---
---
> [INPLACE-195] QR코드 에러 해결

- backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceControllerApiSpec.java
- name -> placeName으로 변경하였습니다.
---
---
---
> [INPLACE-197] 쿼리파라미터 이름 변경

- backend/src/main/java/team7/inplace/admin/crawling/application/CrawlingFacade.java
- backend/src/main/resources/application-crawling.yaml
- backend/src/main/resources/application.yaml
- 스케쥴링 로직을 환경변수로 변경
- Prod가 아닐 경우 '-'를 설정해 스케쥴링이 되지 않도록 변경하였습니다.
---
각자 갖고 계신 env파일에 다음을 추가해주시면 될 것 같습니다.
'''text
UPDATE_VIDEO_TIME_CRON='-'
UPDATE_VIDEO_VIEW_TIME_CRON='-'
'''
---
---
> [INPLACE-196] dev서버에서는 크롤링 되지 않도록 변경

- backend/src/main/java/team7/inplace/admin/crawling/application/CrawlingFacade.java
- backend/src/main/java/team7/inplace/admin/crawling/application/YoutubeCrawlingService.java
- backend/src/main/java/team7/inplace/admin/crawling/client/YoutubeClient.java
- backend/src/main/java/team7/inplace/video/application/command/VideoCommand.java
- 크롤링 매서드를 리팩토링했습니다.
- JsonNode를 파싱할 수 없는경우(일반적이지 않은 JSON) 에러로그를 추가했습니다.
---
- Loki로 Log 따로 저장해야할 것 같스빈다.
---
---
> [INPLACE-198] 크롤링 로직 에러 핸들링

- backend/src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
- Referer 검증을 삭제했습니다.
- 추후 다른방법으로 논의 예정입니다.
---
---
---
> [INPLACE-199] Referer 확인 삭제

- backend/src/main/java/team7/inplace/security/filter/ApiExecutionMetricsFilter.java
- backend/src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
- Admin페이지 Referer 헤더 미포함으로 인해 검증 로직 삭제
---
---
---
> [Release] DEV to PROD 2024_04_02

- backend/src/main/java/team7/inplace/search/application/SearchService.java
- 타입이 바뀌어있던 것을 수정햇습니다.
---
---
---
> [INPLACE-202] 자동완성 타입 오류 수정

- backend/src/main/java/team7/inplace/admin/AdminPageController.java
- backend/src/main/java/team7/inplace/video/persistence/VideoRepository.java
- backend/src/main/resources/templates/admin/video.html
- 인플루언서 필터링을 추가했습니다.
- admin페이지 총 페이징 갯수 오류를 수정하였습니다.
- 페이지 정보를 추가하였습니다.
---
---
---
> [INPLACE-203] Admin페이지에 인플루언서 필터링 추가

- .github/workflows/frontend-ci-cd.yml
- frontend/index.html
- frontend/src/provider/ABTest/index.tsx
- frontend/src/utils/test/testUtils.tsx
* [INPLACE-207] 메인 테스트 오류 해결
* [INPLACE-207] 액션 버전 변경
* [INPLACE-207] 프로젝트 타이틀 수정
---
---
---
[INPLACE-207]: https://justnowthatplace.atlassian.net/browse/INPLACE-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INPLACE-207]: https://justnowthatplace.atlassian.net/browse/INPLACE-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INPLACE-207]: https://justnowthatplace.atlassian.net/browse/INPLACE-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Release] DEV to PROD 2024_04_08

- backend/src/main/java/team7/inplace/security/config/JwtProperties.java
- backend/src/main/java/team7/inplace/security/util/JwtUtil.java
- backend/src/main/resources/application-security.yaml
- 어드민 토큰 만료 시간 1시간으로 늘림
---
- 코드 확인되면 시크릿 env에 추가하겠습니다
---
---
> [INPLACE-208] 어드민 토큰 만료 시간 증가

- backend/src/main/java/team7/inplace/security/config/JwtProperties.java
- backend/src/main/java/team7/inplace/security/util/JwtUtil.java
- backend/src/main/resources/application-security.yaml
> [Release] DEV to PROD 2024_04_12

- backend/src/main/resources/application-db.yaml
- backend/src/main/resources/application.yaml
- production 환경에서 JPA로그가 출력되지 않도록 변경
---
---
---
> [INPLACE-215] JPA 로그레벨 조정

- backend/src/main/java/team7/inplace/global/exception/code/UserErrorCode.java
- backend/src/main/java/team7/inplace/security/util/AuthorizationUtil.java
- backend/src/main/java/team7/inplace/token/application/OauthTokenService.java
- backend/src/main/java/team7/inplace/token/client/KakaoOauthClient.java
- backend/src/main/java/team7/inplace/user/application/UserFacade.java
- backend/src/main/java/team7/inplace/user/application/UserService.java
- backend/src/main/java/team7/inplace/user/presentation/UserController.java
- backend/src/main/java/team7/inplace/user/presentation/UserControllerApiSepc.java
- backend/src/main/java/team7/inplace/user/presentation/UserControllerApiSpec.java
- backend/src/main/java/team7/inplace/video/application/VideoFacade.java
- backend/src/main/java/team7/inplace/video/application/VideoService.java
- 회원탈퇴 API 추가
- Authorization Util을 좀더 사용하기 편하게 수정
---
---
---
> [INPLACE-209] 회원탈퇴 API 추가

- backend/src/main/java/team7/inplace/influencer/application/InfluencerService.java
- backend/src/main/java/team7/inplace/kakao/application/PlaceMessageFacade.java
- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
- backend/src/main/java/team7/inplace/place/application/PlaceService.java
- backend/src/main/java/team7/inplace/place/application/dto/PlaceInfo.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepository.java
- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/persistence/dto/PlaceQueryResult.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceControllerApiSpec.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- backend/src/main/java/team7/inplace/qrcode/application/QRCodeFacade.java
- backend/src/main/java/team7/inplace/review/application/ReviewService.java
- backend/src/main/java/team7/inplace/search/application/SearchService.java
- backend/src/main/java/team7/inplace/security/application/CurrentUserProvider.java
- backend/src/main/java/team7/inplace/security/filter/AuthorizationFilter.java
- backend/src/main/java/team7/inplace/security/filter/ExceptionHandlingFilter.java
- backend/src/main/java/team7/inplace/security/util/AuthorizationUtil.java
- backend/src/main/java/team7/inplace/user/application/UserFacade.java
- backend/src/main/java/team7/inplace/video/application/VideoFacade.java
- backend/src/test/java/team7/inplace/place/persistence/PlaceReadRepositoryTest.java
- AuthorizationUtil의 getUserId를 Optional로 변경하였습니다.
- null을 사용하는 쿼리가 몇개 있어서 Optional로 변경했습니다.
- 이부분에 관해 논의사항은 아래 추가하겠습니다.
- SelfJoin을 통해 Place에 좋아요한 사람 수 및, SelfLike 여부를 추가했습니다.
---
AuthorizationUtil에서 Optional을 반환하게 하면, null이 필요한 기능의 경우 orElseGet을 해야하는 불편함이 있습니다.
그래서 getUserIdOrElseThrow와, getUserIdOrGetNull, 같이 throw를 하는 매서드와 null을 반환하는 매서드로 분리하는게  좋을 것 같습니다.
이에 관한 의견 부탁드립니다.
```java
public static Long getUserIdOrElseGetNull() {
if (isNotLoginUser()) {
return null;
}
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
CustomOAuth2User customOAuth2User = (CustomOAuth2User) authentication.getPrincipal();
return customOAuth2User.id();
}
public static Long getUserIdOrElseThrow() {
checkLoginUser();
Authentication authentication = …
```
> [INPLACE-210] 장소 좋아요 개수 반환 추가

- backend/src/main/java/team7/inplace/video/application/VideoFacade.java
- backend/src/main/java/team7/inplace/video/application/VideoService.java
- backend/src/main/java/team7/inplace/video/domain/CoolVideo.java
- backend/src/main/java/team7/inplace/video/domain/RecentVideo.java
- backend/src/main/java/team7/inplace/video/persistence/VideoReadRepository.java
- backend/src/main/java/team7/inplace/video/persistence/VideoReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/video/persistence/dto/VideoQueryResult.java
- backend/src/main/java/team7/inplace/video/presentation/VideoController.java
- backend/src/main/java/team7/inplace/video/presentation/VideoControllerApiSpec.java
- backend/src/main/java/team7/inplace/video/presentation/dto/VideoResponse.java
- backend/src/test/java/team7/inplace/video/persistence/VideoReadRepositoryTest.java
Reverts team-inplace/inplace#267
> Revert "[INPLACE-211] 비디오 반환 값 수정"

- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- 구글 리뷰 좋아요 4점이상 true 
---
---
---
> [INPLACE-212] 구글 리뷰 좋아요 기준 4점으로 수정

- backend/src/main/java/team7/inplace/influencer/application/InfluencerService.java
- backend/src/main/java/team7/inplace/kakao/application/PlaceMessageFacade.java
- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
- backend/src/main/java/team7/inplace/qrcode/application/QRCodeFacade.java
- backend/src/main/java/team7/inplace/review/application/ReviewService.java
- backend/src/main/java/team7/inplace/search/application/SearchService.java
- backend/src/main/java/team7/inplace/security/application/CurrentUserProvider.java
- backend/src/main/java/team7/inplace/security/util/AuthorizationUtil.java
- backend/src/main/java/team7/inplace/user/application/UserFacade.java
- backend/src/main/java/team7/inplace/video/application/VideoFacade.java
- backend/src/test/java/team7/inplace/influencer/application/InfluencerServiceTest.java
- backend/src/test/java/team7/inplace/review/application/ReviewServiceTest.java
- getUsername -> 삭제
- getUserId -> getUserIdOrNull, getUserIdOrThrow 로 분리
---
---
---
> [INPLACE-223] AuthorizationUtil 수정

- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/search/persistence/VideoSearchRepository.java
- backend/src/main/java/team7/inplace/video/persistence/VideoReadRepositoryImpl.java
- Video에서 placeId를 비교하는 쿼리를 변경했습니다.
---
---
---
> [INPLACE-229] 누락된 조건 추가

- backend/.gitignore
- backend/src/main/java/team7/inplace/admin/AdminPageController.java
- backend/src/main/resources/messages.properties
- backend/src/main/resources/static/css/style.css
- backend/src/main/resources/static/js/banner.js
- backend/src/main/resources/static/js/fragment/modal.js
- backend/src/main/resources/static/js/influencer/list.js
- backend/src/main/resources/static/js/influencer/new.js
- backend/src/main/resources/static/js/main.js
- backend/src/main/resources/static/js/video.js
- backend/src/main/resources/templates/admin/banner.html
- backend/src/main/resources/templates/admin/influencer/list.html
- backend/src/main/resources/templates/admin/influencer/new.html
- backend/src/main/resources/templates/admin/login.html
- backend/src/main/resources/templates/admin/main.html
- backend/src/main/resources/templates/admin/video.html
- backend/src/main/resources/templates/fragment/header.html
- backend/src/main/resources/templates/fragment/modal.html
- backend/src/main/resources/templates/layout/base.html
- 공통 fragment는 fragment 파일에서 관리합니다. (modal)
- messages.properties 파일을 추가하였습니다.
- 인플루언서 수정 로직 오류를 수정하였습니다.
---
- modal open 관련 js를 모두 modal 쪽으로 옮기려다가 각 영역마다 사용하는 모달의 종류가 달라서 그냥 각 js 파일에 넣어두었습니다.
- 마지막 commit 오타 / 모든 modal(x) -> 모든 video (o)
---
---
> [INPLACE-255] admin page 정리

- backend/src/main/resources/messages.properties
- backend/src/main/resources/static/css/video.css
- backend/src/main/resources/static/js/video.js
- backend/src/main/resources/templates/admin/video.html
- video 등록 모달을 수정하였습니다.
---
다음과 같은 모습입니다.
- 장소 검색 후 등록 시, 그에 맞는 input field가 채워집니다.
- google id는 없어도 등록이 가능합니다.
---
---
> [INPLACE-205] google id 없이 장소 등록

- backend/src/main/java/team7/inplace/influencer/application/InfluencerService.java
- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerReadRepository.java
- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/influencer/persistence/InfluencerRepository.java
- backend/src/test/java/team7/inplace/influencer/application/InfluencerServiceTest.java
- backend/src/test/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImplTest.java
- 페이지 내에 있는 인플루언서만 좋아요순으로 정렬되는 문제를 수정했습니다.
- 쿼리 자체에서 좋아요한 인플루언서를 기준으로 sorting되도록 수정했습니다.
---
---
---
> [INPLACE-232] 인플루언서 조회 페이지네이션 수정

- frontend/src/api/hooks/useGetDropdownCategory.ts
- frontend/src/mocks/mapHandlers.ts
> [INPLACE-233] 장소 카테고리 api 경로 수정

- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/video/persistence/VideoReadRepositoryImpl.java
- JoinTable에서 Video가 없는 경우로 인해 쿼리를 innerJoin으로 변경했습니다.
- null이 필요한 Video를 조회하는 쿼리를 분리했습니다.
- 필요없는 조건절을 삭제했습니다.
---
---
---
> [INPLACE-235] Place/Video InnerJoin으로 변경

- frontend/src/components/Map/MapWindow/index.tsx
- eats / plays에 따라 핀 다르게 조정
---
---
---
> [INPLACE-237] 마커 핀 type eats로 변경

- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/persistence/dto/PlaceQueryResult.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- 마커 반환 시 카테고리 타입 추가
---
---
---
> [INPLACE-236] marker 정보에 카테고리 타입 추가

- backend/src/main/java/team7/inplace/place/persistence/PlaceReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/place/persistence/dto/PlaceQueryResult.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- frontend/src/components/Map/MapWindow/index.tsx
> [Release] DEV to PROD 2024_05_19 ver 2

- backend/src/main/java/team7/inplace/search/application/SearchService.java
- backend/src/main/java/team7/inplace/search/persistence/VideoSearchRepository.java
- backend/src/main/java/team7/inplace/search/presentation/SearchController.java
- backend/src/main/java/team7/inplace/search/presentation/SearchControllerApiSpec.java
- 검색 결과 데이터를 수정했습니다.
---
---
---
> [INPLACE-239] 비디오 검색에 장소 정보 추가

- backend/src/main/java/team7/inplace/search/application/SearchService.java
- backend/src/main/java/team7/inplace/search/persistence/VideoSearchRepository.java
- backend/src/main/java/team7/inplace/search/presentation/SearchController.java
- backend/src/main/java/team7/inplace/search/presentation/SearchControllerApiSpec.java
- 누락된 api 수정을 추가했습니다.
---
---
---
> [Release] DEV to PROD 2024_05_19 ver 3

- .github/workflows/frontend-ci-cd.yml
- frontend/index.html
- frontend/src/provider/ABTest/index.tsx
- frontend/src/setupTests.ts
- frontend/src/test/likeUnlike.test.tsx
- frontend/src/test/searchData.test.tsx
- frontend/src/utils/test/googleTestUtils.tsx
> [Release] DEV to PROD 2024_05_20

- backend/src/main/java/team7/inplace/admin/AdminPageController.java
- backend/src/main/java/team7/inplace/admin/dto/CategoryForm.java
- backend/src/main/java/team7/inplace/global/exception/code/CategoryErrorCode.java
- backend/src/main/java/team7/inplace/place/application/PlaceFacade.java
- backend/src/main/java/team7/inplace/place/application/PlaceService.java
- backend/src/main/java/team7/inplace/place/application/dto/PlaceInfo.java
- backend/src/main/java/team7/inplace/place/domain/Category.java
- backend/src/main/java/team7/inplace/place/persistence/CategoryRepository.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
- backend/src/main/java/team7/inplace/place/presentation/PlaceControllerApiSpec.java
- backend/src/main/java/team7/inplace/place/presentation/dto/PlacesResponse.java
- backend/src/main/resources/static/css/category/form.css
- backend/src/main/resources/static/css/category/list.css
- backend/src/main/resources/static/js/category/list.js
- backend/src/main/resources/templates/admin/category/add.html
- backend/src/main/resources/templates/admin/category/edit.html
- backend/src/main/resources/templates/admin/category/list.html
- backend/src/main/resources/templates/fragment/header.html
* [INPLACE-241] 어드민 페이지 parentCategory 조회
* [INPLACE-241] category 수정 기능
* [INPLACE-241] subCategory 조회
* [INPLACE-241] video 등록시 subCategory로만 등록
* [INPLACE-241] category 추가 기능
* [INPLACE-241] category 삭제 기능
---
---
---
[INPLACE-241]: https://justnowthatplace.atlassian.net/browse/INPLACE-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INPLACE-241]: https://justnowthatplace.atlassian.net/browse/INPLACE-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INPLACE-241]: https://justnowthatplace.atlassian.net/browse/INPLACE-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INPLACE-241]: https://justnowthatplace.atlassian.net/browse/INPLACE-241?atlOrigi …
> [Release] DEV to PROD 2024_05_20 ver2

- backend/src/main/java/team7/inplace/post/application/PostFacade.java
- backend/src/main/java/team7/inplace/post/application/PostService.java
- backend/src/main/java/team7/inplace/post/persistence/PostReadRepository.java
- backend/src/main/java/team7/inplace/post/persistence/PostReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/post/persistence/dto/PostQueryResult.java
- backend/src/main/java/team7/inplace/post/presentation/PostController.java
- backend/src/main/java/team7/inplace/post/presentation/PostControllerApiSpec.java
- backend/src/main/java/team7/inplace/post/presentation/dto/PostResponse.java
- backend/src/test/java/team7/inplace/post/persistence/PostReadRepositoryImplTest.java
- backend/src/test/resources/sql/test-post.sql
- 댓글 언급 기능에 사용할 자동완성 기능을 추가했습니다.
---
---
---
> [INPLACE-255] 댓글 언급 기능 추가

- backend/Dockerfile
- backend/src/main/java/team7/inplace/place/client/GooglePlaceClient.java
> [INPLACE-257] ipv6 테스트

- backend/src/main/java/team7/inplace/admin/AdminPageController.java
- backend/src/main/java/team7/inplace/post/application/PostService.java
- backend/src/main/java/team7/inplace/post/domain/Comment.java
- backend/src/main/java/team7/inplace/post/domain/Post.java
- backend/src/main/java/team7/inplace/post/persistence/CommentJpaRepository.java
- backend/src/main/java/team7/inplace/post/persistence/PostJpaRepository.java
- backend/src/main/resources/static/css/report.css
- backend/src/main/resources/static/js/report.js
- backend/src/main/resources/templates/admin/report.html
- backend/src/main/resources/templates/fragment/header.html
- backend/src/test/java/team7/inplace/influencer/persistence/InfluencerReadRepositoryImplTest.java
- backend/src/test/java/team7/inplace/place/persistence/PlaceReadRepositoryTest.java
- backend/src/test/java/team7/inplace/post/persistence/CommentReadRepositoryTest.java
- backend/src/test/java/team7/inplace/review/persistence/ReviewReadRepositoryImplTest.java
- backend/src/test/java/team7/inplace/video/persistence/VideoReadRepositoryTest.java
- 신고 받았는데 ai로 안 잡힌 것들 관리자 페이지에서 처리할 수 있도록 페이지 추가
- 내용 부분 클릭시 전체 내용 확인 가능
---
---
---
> [INPLACE-262] 어드민 신고 관리 페이지 추가

- .github/workflows/backend-ci-cd-test.yml
> [INPLACE-267] CICD 명령어 수정

- backend/src/main/java/team7/inplace/post/persistence/CommentReadRepositoryImpl.java
- backend/src/test/java/team7/inplace/post/persistence/CommentReadRepositoryTest.java
- backend/src/test/resources/sql/test-comment.sql
- QueryDSL 쿼리 오류를 수정하였습니다.
- 테스트 코드를 작성했습니다.
---
---
---
> [INPLACE-269] 내 댓글이 확인되지 않는 문제 수정

- backend/src/main/java/team7/inplace/post/persistence/CommentReadRepositoryImpl.java
- backend/src/main/java/team7/inplace/post/persistence/PostReadRepositoryImpl.java
- backend/src/test/java/team7/inplace/post/persistence/CommentReadRepositoryTest.java
- backend/src/test/java/team7/inplace/post/persistence/PostReadRepositoryImplTest.java
- backend/src/test/resources/sql/test-comment.sql
- backend/src/test/resources/sql/test-post.sql
- SoftDelete 관련해 where절을 추가하였습니다.
---
---
---
> [INPLACE-277] post/comments SoftDelete 쿼리 추가

- backend/src/main/java/team7/inplace/post/presentation/PostController.java
- backend/src/main/java/team7/inplace/post/presentation/PostControllerApiSpec.java
> [INPLACE-274] PostMapping 추가 및 URL 변경

- .github/workflows/backend-ci-cd-production.yml
> [INPLACE-280] 단일서버 배포로 워크플로우 수정

- .github/workflows/backend-ci-cd-production.yml
> [INPLACE-280] 이전 컨테이너 종료 및 이름변경 단계 수정

- backend/build.gradle
> [INPLACE-281] 루트 springframework.boot 삭제

- frontend/mobile/package.json
- frontend/pnpm-lock.yaml
- frontend/web/src/components/common/layouts/Header/AuthButtonsB.tsx
> [INPLACE-287] 알림 기능 추가하면서 발생한 오류 수정

- .github/workflows/backend-ci-cd-production.yml
- .github/workflows/backend-ci-cd-test.yml
> [INPLACE-284] base64를 디코딩하도록 변경

- backend/inplace-api/build.gradle
- backend/inplace-api/src/main/java/place/PlaceController.java
- backend/inplace-api/src/main/java/place/dto/PlaceRequest.java
- backend/inplace-api/src/main/java/place/dto/PlaceResponse.java
- backend/inplace-api/src/main/java/place/dto/ReviewResponse.java
- backend/inplace-application/src/main/java/place/query/PlaceQueryFacade.java
- backend/inplace-application/src/main/java/place/query/dto/GooglePlaceResult.java
- backend/inplace-application/src/main/java/place/query/dto/PlaceResult.java
- backend/inplace-application/src/main/java/review/ReviewService.java
- backend/inplace-application/src/main/java/review/dto/ReviewResult.java
- api 모듈 place 파트의 모든 에러를 수정하였습니다.
---
- GooglePlaceResponse는 GooglePlaceResult로 변환하여 Facade dto로 넘기는 것으로 종속성 문제를 해결하였습니다.
---
---
> [INPLACE-285] api 모듈 place 파트 오류 수정

- backend/inplace-api/src/main/java/post/dto/PostResponse.java
- backend/inplace-application/src/main/java/post/query/PostQueryFacade.java
- backend/inplace-application/src/main/java/post/query/PostQueryService.java
- backend/inplace-common/src/main/java/cursor/CursorResult.java
- backend/inplace-domain/build.gradle
- backend/inplace-domain/src/main/java/post/PostPhoto.java
- backend/inplace-domain/src/main/java/post/query/PostReadRepository.java
- backend/inplace-infra/build.gradle
- backend/inplace-infra/src/main/java/influencer/InfluencerReadQueryDslRepository.java
- backend/inplace-infra/src/main/java/place/PlaceReadQueryDslRepositoryImpl.java
- backend/inplace-infra/src/main/java/post/CommentReadQueryDslRepository.java
- backend/inplace-infra/src/main/java/post/PostReadQueryDslRepository.java
- backend/inplace-infra/src/main/java/review/ReviewReadQueryDslRepository.java
- backend/inplace-infra/src/main/java/search/InfluencerSearchQueryDslRepository.java
- backend/inplace-infra/src/main/java/search/PlaceSearchQueryDslRepository.java
- backend/inplace-infra/src/main/java/search/VideoSearchQueryDslRepository.java
- backend/inplace-infra/src/main/java/user/UserReadQueryDslRepository.java
- backend/inplace-infra/src/main/java/video/VideoReadQueryDslRepository.java
- backend/src/test/java/team7/inplace/place/persistence/PlaceReadRepositoryTest.java
- backend/src/test/java/team7/inplace/post/persistence/CommentReadRepositoryTest.java
- backend/src/test/java/team7/inplace/post/persistence/PostReadRepositoryImplTest.java
- api 모듈 및 infra쪽 변경했습니다.
---
---
---
> [INPLACE-285] post 모듈 변경

- backend/inplace-domain/src/main/java/my/inplace/domain/post/query/PostQueryResult.java
> [INPLACE-295] jsonNode -> Image 객체 변경
